name: Get announcements

on:
  push:
    paths:
      - 'dist/**'
      - '.github/workflows/**'
  schedule:
    # https://crontab.guru
    - cron: '16 6/3 * * 1-5'
    - cron: '43 10,16,20 * * 6,0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Retrieving the dependencies
      run: yarn
    - name: Get the announcements
      run: node ./dist/index.js
    - name: Clone the artifact repository (A.R.)
      run: |
        git clone https://.:${{ secrets.SCHWEB_TOKEN }}@github.com/smhs-os-project/smhs-announcements ../announce
    - name: Copy the artifacts to the A.R.
      run: cp ./data/* ../announce
    - name: Commit and push to A.R.
      run: |
        cd ../announce
        git config user.email "sw@imych.one"
        git config user.name "SMHS Open Source Organization"
        git add -A
        git commit -m "update the announcement"
        git push -f
