name: Test the code with Jest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Retrieving the dependencies
      run: yarn -D
    - name: Test
      run: yarn test
